theme: jekyll-theme-midnight
markdown: kramdown
kramdown:
  math_engine: mathjax
title: Geometric Algebra Cheat Sheet
description: Identities and key results in Geometric Algebra that are useful to me and hopefully others
show_downloads: false
